### PR TITLE
Gr/parsing overhaul

### PR DESCRIPTION
**Pull request by GeorgeR227**
This pull request is meant to improve the parsing and creation of Decapodes.

### CODE REVIEW

**Comment by lukem12345** [comment]
Commit f4c5a1e fixes a hitherto unknown bug with a composed vector of functions applied to two variables, i.e. a chain of Op2s. The computational meaning of a chain of operators such as `C == \circ(f,g)(A,B)` is not yet decided. This could mean that the function `g` is an Op2 as we typically understand it, and `f` is an Op1, or it could mean that `g` is an Op2 as we typically understand it, and `f` is an Op2 that takes a copy of `g(A,B)` as its two arguments.

No Decapode use cases have run into this scenario before, so how to compile this is still unknown. The `compile` function should be amended to check if an `:op2` is a vector, and raise a legible error if so.

**Comment by lukem12345** [comment]
Currently, the following Decapode does not parse:
```julia
G = SummationDecapode(parse_decapode(quote
    (A,B,C,D,E)::infer{X}
    B == ∘(g)(f(A))
    E == ∘(h)(f(C,D))
end))
```
`g` and `h` should both be recognized as Op1s.

**Comment by GeorgeR227** [comment]
I believe that issue should be solved by commit a3b1d7f.

**Comment by lukem12345** [comment]
New features that this branch allows are:

[ ] - No need to parameterize forms over space (i.e. {X})
[ ] - #94 Literals
[ ] - Multiplication without parentheses
[ ] - Variables do not need to be declared before being used
[ ] - Fix #84 Tvar parsing

**Pull request merged**
