### PR TITLE
Add docs fixes

### LINKED ISSUE #127: Amend Docs
There are a few shortcomings in the current docs that should be fixed.

- [x] Add a LaTeX version of the exterior calculus formulation of Halfar’s equation 2.
- [x] Make sure that the 2D plane mesh for glacial dynamics is loaded in correctly.

### PR DESCRIPTION
**Pull request by lukem12345**
Close #127

### CODE REVIEW

**Comment by jpfairbanks** [comment]
It looks like this closes just the climate model docs problems, but we still need to update the old examples

**Comment by jpfairbanks** [comment]
@lukem12345 ready to merge this?

**Comment by lukem12345** [comment]
@jpfairbanks Not yet, but I'll push docs changes that I have made. Some of the encoding of boundary conditions in the Poiseuille flow were handled strangely before we settled on current best practices. Also, need to double-check Diffusion-Advection and Boundary Conditions pages

**Review by jpfairbanks — APPROVED** [review]

**Comment by lukem12345** [comment]
Going to push fixes for `overview.md` and `boundary_conditions.md` in a few.

**Comment by jpfairbanks** [comment]
Nice, I am working on a new docs page using simple equations to go after overview for ASKEM.

**Comment by lukem12345** [comment]
Great!

On an editorial note:

I am wondering what the value we are getting out of using the `star d star d` formulation for diffusion is in our docs.

Defining diffusion/ the Laplacian this way:
- educates readers somewhat on the Exterior Calculus
- demonstrates the elegance of the DEC
- it is only a difference of 3 symbols to write one instead of the other
- the `star d star d` formulation is nicer if you want to build up simulations using only things you find directly in the de Rham complex
- not using Delta reduces the number of distinct symbols on the screen

However:
I think it should be used in examples only where the author wishes to educate readers on the definition of the Laplacian:
- this symbol is already recognizable to readers
- this is how users write Decapodes in practice
- via overload resolution, the Laplacian may automatically take the `d del + del d` form when the argument is a 1 form

I think making this change is a demonstration of the principle that composition should be performed:
- to reduce cognitive load
- in anticipation of components to be swapped out
- to express some physical intuition (e.g. magnetics is separate from hydrodynamics in MHD)
- for education's sake

Without any of the above reasons, it delves somewhat into composition for composition's sake.

**Comment by jpfairbanks** [comment]
I think it would be fine to use Laplacian everywhere we do diffusion and add a new docs page showing composition and aliases. I'll make a new issue to track composite operators. I'd like to get the old docs restored to main ASAP and then address general docs improvement in additional PRs

**Comment by jpfairbanks** [comment]
I did the merge conflicts

**Comment by lukem12345** [comment]
Added in versions of BC and Overview that should be correct barring git pulling and pushing doing odd things.

Poiseuille is partially fixed. The way that boundary conditions happened in the original Poiseuille doc was against current conventions, so this page has taken longer to work through. It will be shorter and clearer after that process is done, which is good.

In the meantime, BC and Overview docs can be merged through whatever git strategies of choice. (cherry-pick overview and bc changes onto a different branch, make a commit that removes changes to Poiseuille in this branch, etc.)

**Comment by lukem12345** [comment]
Looks like the environment on the GitHub action is slightly different than my local system for whatever reason. Some paths are getting mixed. I'll change some relative paths.

**Review by jpfairbanks — APPROVED** [review]

**Comment by jpfairbanks** [comment]
I'm going to merge this and if you have more docs updates, they can go in a new PR.

**Pull request merged**
