### PR TITLE
add pressure flow simulation

### PR DESCRIPTION
**Pull request by jpfairbanks**
@bosonbaas, if you could take a look at my PressureFlow simulation and see why it is so unstable, that would be very helpful. 

I tried the following, which I thought would work with the right constants, but it is very unstable with even a tiny viscosity term.

```julia
PressureFlow = quote
  # state variables
  V::Form1{X}
  P::Form0{X}

  # derived quantities
  ΔV::Form1{X}
  ∇P::Form0{X}
  ΔP::Form0{X}
  ϕₚ::Form1{X}

  # tanvars
  V̇::Form1{X}
  Ṗ::Form0{X}
  ∂ₜ(V) == V̇
  ∂ₜ(P) == Ṗ
  
  ∇P == d₀(P)
  ΔV == Δ₁(V)
  ΔP == Δ₀(P)

  V̇  == α(∇P) + μ(ΔV)
  ϕₚ == γ(-(L₀(V, P))) 
  Ṗ == β(Δ₀(P)) + ∘(dual_d₁,⋆₀⁻¹)(ϕₚ)
  # Ṗ  == ϕₚ
end

pf = SummationDecapode(parse_decapode(PressureFlow))

flatten_form(vfield::Function, mesh) =  ♭(mesh, DualVectorField(vfield.(mesh[triangle_center(mesh),:dual_point])))

function generate(sd, my_symbol; hodge=GeometricHodge())
  i0 = (v,x) -> ⋆(1, sd, hodge=hodge)*wedge_product(Tuple{0,1}, sd, v, inv_hodge_star(0,sd, hodge=DiagonalHodge())*x)
  op = @match my_symbol begin
    :k => x->2000x
    :μ => x->-0.0001x
    # :μ => x->-2000x
    :α => x->0*x
    :β => x->2000*x
    :γ => x->1*x
    :⋆₀ => x->⋆(0,sd,hodge=hodge)*x
    :⋆₁ => x->⋆(1, sd, hodge=hodge)*x
    :⋆₀⁻¹ => x->inv_hodge_star(0,sd, x; hodge=hodge)
    :⋆₁⁻¹ => x->inv_hodge_star(1,sd,hodge=hodge)*x
    :d₀ => x->d(0,sd)*x
    :d₁ => x->d(1,sd)*x
    :dual_d₀ => x->dual_derivative(0,sd)*x
    :dual_d₁ => x->dual_derivative(1,sd)*x
    :∧₀₁ => (x,y)-> wedge_product(Tuple{0,1}, sd, x, y)
    :plus => (+)
    :(-) => x-> -x
    # :L₀ => (v,x)->dual_derivative(1, sd)*(i0(v, x))
    :L₀ => (v,x)->begin
      # dual_derivative(1, sd)*⋆(1, sd)*wedge_product(Tuple{1,0}, sd, v, x)
      ⋆(1, sd; hodge=hodge)*wedge_product(Tuple{1,0}, sd, v, x)
    end
    :i₀ => i0 
    :Δ₀ => x -> begin # dδ
      δ(1, sd, d(0, sd)*x, hodge=hodge) end
    # :Δ₀ => x -> begin # d ⋆ d̃ ⋆⁻¹
    #   y = dual_derivative(1,sd)*⋆(1, sd, hodge=hodge)*d(0,sd)*x
    #   inv_hodge_star(0,sd, y; hodge=hodge)
    # end
    :Δ₁ => x -> begin # dδ + δd
      δ(2, sd, d(1, sd)*x, hodge=hodge) + d(0, sd)*δ(1, sd, x, hodge=hodge)
    end

    # :Δ₁ => x -> begin # d ⋆ d̃ ⋆⁻¹ + ⋆ d̃ ⋆ d
    #   y = dual_derivative(0,sd)*⋆(2, sd, hodge=hodge)*d(1,sd)*x
    #   inv_hodge_star(2,sd, y; hodge=hodge) 
    #   z = d(0, sd) * inverse_hode_star(2, sd, dual_derivative(1, sd)*⋆(1,sd, hodge=hodge)*x; hodge=hodge)
    #   return y + z
    # end
  end
  return (args...) ->  op(args...)
end
```

There are a bunch of averaging and divergence operations in the Navier-Stokes example

```julia
NavierStokes = quote
  V::Form1{X}
  V̇::Form1{X}
  G::Form1{X}
  T::Form0{X}
  ρ::Form0{X}
  ṗ::Form0{X}
  p::Form0{X}
  

  V̇ == neg₁(L₁′(V, V)) + 
        div₁(kᵥ(Δ₁(V) + third(d₀(δ₁(V)))), avg₀₁(ρ)) +
        d₀(half(i₁′(V, V))) +
        neg₁(div₁(d₀(p),avg₀₁(ρ))) +
        G
  ∂ₜ(V) == V̇
  ṗ == neg₀(⋆₀⁻¹(L₀(V, ⋆₀(p))))# + ⋆₀⁻¹(dual_d₁(⋆₁(kᵨ(d₀(ρ)))))
  ∂ₜ(p) == ṗ
end
```
Plus the equations of state coupling that we had. I guess we could try a potential flow situation to see if that works. I remember that we had a working potential flow before we had a working general flow.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
The original CHT benchmark code is here https://github.com/AlgebraicJulia/DECAPODES-Benchmarks/blob/main/simulations/cht/DEC/physics.jl

**Comment by JDCampII** [comment]
Will begin looking at various values for alpha, beta, and gamma to determine when we start running into errors.

**Comment by jpfairbanks** [comment]
@lukem12345, do you have an update version of this that is using the icosphere mesh? I've merged a few PRs to main. Getting that icosphere mesh running will really make the debugging of these physics easier.

**Comment by lukem12345** [comment]
@jpfairbanks Please see #63

**Pull request merged**
