### PR TITLE
ENH: Add Poiseuille flow example problem

### PR DESCRIPTION
**Pull request by bosonbaas**
The keyword argument `form2dim` for `gen_sim` in Simulations.jl was not actually being used. This PR corrects that error.

### CODE REVIEW

**Comment by bosonbaas** [comment]
This PR has now been changed to contain the Poiseuille flow example, the original PR has been resolved.

**Comment by jpfairbanks** [comment]
@bosonbaas is this ready to merge?

**Comment by bosonbaas** [comment]
Were we wanting to include this in a Documentation page? If not, I think the final things to do before we move it to the `examples` folder is to add explanatory comments and remove the `Manifest.toml` file. I'll be going through and removing most of the existing files in the `examples` folder, since they're either out of date or have been moved to Decapodes_Benchmarks.

**Comment by jpfairbanks** [comment]
Let's delete the manifest and add the comments and merge. Then move to docs in a second PR so that we aren't held up by it

**Comment by bosonbaas** [comment]
Gotcha. Registration of this package isn't being held up by this PR if that's your concern. But wouldn't be a problem to have these in 2 PRs

**Comment by jpfairbanks** [comment]
I'm not concerned about that I'm just trying to minimize the longstanding open PRs. If we don't reformat this for docs tomorrow it might not happen for a few weeks. And I don't want to delay having the example that long.

**Pull request merged**
