### PR TITLE
Add Gray Scott model

### PR DESCRIPTION
**Pull request by lukem12345**
Add an example of the Gray Scott chemical reaction model as a Decapode.

I will leave this as a draft until I study this model some more and verify that the phenomena that we observe are correct.

This should also be managed using the DrWatson.jl system along with the current Brusselator example.

gray_scott
gray_scott_sphere_compressed

### CODE REVIEW

**Comment by jpfairbanks** [comment]
These look pretty good!

**Comment by lukem12345** [comment]
gray_scott_here

**Comment by lukem12345** [comment]
There's a merge conflict that I'll look at later. The current `gray_scott.jl` script is updated to the most recent version of Decapodes, and so can be downloaded and run there

**Comment by jpfairbanks** [comment]
I think that was a false positive on the merge conflict. I just did a git merge locally and it reported no conflicts.

**Comment by lukem12345** [comment]
> 

Great, feel free to merge in Gray-Scott pending your review.

**Review by jpfairbanks — APPROVED** [review]

**Comment by jpfairbanks** [comment]
Approved, just waiting for tests

**Pull request merged**
