### PR TITLE
Cm/canon oncology

### PR DESCRIPTION
**Pull request by quffaro**
Added Logistic and Gompertz growth models to Canon.Oncology. coded by @lukem12345 @GeorgeR227 and researched by myself

### CODE REVIEW

**Review by jpfairbanks — CHANGES_REQUESTED** [review]
It would really help convince oncology modelers that Decapodes has something to offer them if you could

- pull the logistic and gompertz laws out into their own Decapodes
- do "GrowthDiffusion" as a model that expects a growth law, 
- build these two models with an ocompose, 
- make a docs page running both models and comparing them

The separation of concerns between the local growth law and the diffusion law is really nice because people say "we ran X physics with Y growth term" all the time in MathOnco. This formulation actually embeds that 2D structure into the code.

**Comment by quffaro** [comment]
I agree. Along the same...vein, I've discussed with @lukem12345 last week that a model for angiogenesis in tumor growth appear to be compositions of two growth models, and that we could be a neat compositional example.

**Review by jpfairbanks — APPROVED** [review]

**Comment by lukem12345** [comment]
@quffaro I know that you will be further investigating applications, but is this PR ready to merge?

**Comment by lukem12345** [comment]
@quffaro In the future please squash

**Pull request merged**
