### PR TITLE
Boundary Conditions as Collage-Decapodes

### LINKED ISSUE #144: Add support for boundary conditions as Decapode Morphisms
We need to represent the ICs and BCs as morphisms between decapodes (with the natural transformation) and use that to autogenerate the masking operations in the simulator.

From the original paper: https://arxiv.org/pdf/2204.01843.pdf
image

This probably requires implementing profunctor collages in Catlab. 
image

### PR DESCRIPTION
**Pull request by lukem12345**
Closes #144 

With @p-stokes , this branch will encode boundary conditions and initial conditions as morphisms between Decapode diagrams.

One Decapode represents the physical equations, and the other represents values to set along boundaries.

TODO:

- [x] Add docs page
- [x] Pass simple masking test with a discrete boundary Decapode
- [x] Initial conditions

~Pass masking test where a Var in the discrete Decapode is computed from other vars in that Decapode.~
  - This feature is "extra", and so lies out of the scope of this PR.

### CODE REVIEW

**Comment by lukem12345** [comment]
I have marked this PR as "ready for review" since the source code and tests are complete (up to passing the review stage). So, the code and tests themselves are ready to review as I concurrently write the docs and example scripts to accompany this new feature set.
@jpfairbanks @p-stokes

**Comment by jpfairbanks** [comment]
Sadly this didn't get merged before the component-arraypocalypse. so it needs to be brought up to date (@lukem12345). There are also merge conflicts now.

**Comment by lukem12345** [comment]
Disadvantage to not using `findnode` as a thin wrapper around `getfield`, but such is git.

**Comment by lukem12345** [comment]
What are your thoughts on the docs page. Good enough for merge? The accompanying demo is the so-called `brusselator_bounded.jl` example. @jpfairbanks

**Comment by lukem12345** [comment]
DiagrammaticEquations.jl has the collage source and test code now, so this PR is closed by that repo!

**Pull request closed without merging**
