### PR TITLE
Space Weather Example

### PR DESCRIPTION
**Pull request by jpfairbanks**
This is the PR to track @lukem12345 's branch for geospatial mesh development

### CODE REVIEW

**Comment by lukem12345** [comment]
Using `glue_sorted_triangle!` made the code cleaner and shorter.

I can't think of a native way to specify which points and edges form are in the Northern-most parallel on the sphere, so the "(un)-stitching the north pole" problem can be solved via:

- have `makeSphere` also return a range specifying the indices of the vertices in the Northern-most parallel
  - the user is then responsible for adding a North-pole vertex and calling `glue_sorted_triangle!` $numMeridians$ times.
- add a `connectNorthPole` flag which when `true` has `makeSphere` automatically do what was described in the previous sub-bullet

I'll go with the second of these. I'll default `connectNorthPole` to `true`.

I suppose that this naturally implies the usefulness of a `connectSouthPole` flag. This'll also default to `true`.

**Comment by lukem12345** [comment]
Actually, we could instead just infer the `connectNorthPole` and `connectSouthPole` conditions from whether `minLat == 0` and `maxLat == 0`, respectively. This is better.

Just remains to decide how we handle letting the user delete the pole vertices.
I'll have `makeSphere` return a tuple `(sphereMesh, northPoleIdx, southPoleIdx)`, setting an index to 0 if it does not exist.

**Comment by lukem12345** [comment]
The sphere mesh generation is at a good stopping point. There are some nonessential improvements available however.

- Simply calculate the number of vertices we need to create before entering the main loop, and just call `add_vertices!` once.
  - This probably wouldn't give us any performance gains, since the `Point3D` object we use is immutable, so we'd have to calculate these points over again anyway. So only way this approach is viable is if these points can also be calculated ahead of time. This is possible, since you can of course squeeze these range-based calculations into some `map`, but I am afraid of the code becoming too dense to be debugged without gnashing of teeth.
- Separate out the spherical-to-cartesian coordinates helper function into its own function. But this refactor is so quick it can just be done at the time the need arises.
- Provide some helper functions for translating Latitude and Longitude described using the `(degrees, enum{north, south}), (degrees, enum{east, west})` 
  - This is just in-case the parameter conventions that I decided to adopt are too mind-boggling. Hopefully they aren't. I followed the diagram at [the wikipedia page for spherical coordinates](https://en.wikipedia.org/wiki/Spherical_coordinate_system).
- Make some ascii art of the previously-linked diagram to stick in the doc-string.
  - Just for fun. But not happening.
- Benchmark mesh generation.
  - Already super fast on hipergator for TIE-GCM grid, but would be interesting to see the densest grid we can make in < 5 seconds. Not necessary.

Don't want to fall into the trap of trying to makie the world's most feature-complete spherical mesh generator. This just has to be a good-enough sphere-shaped-embedded-deltaset-2d generator.

Before merging I would like to:
- [ ] View a generated mesh using GLMakie
- [ ] Run a simulation on a mesh using the new Decapodes tooling
- [ ] Rebase (always good practice I think)

**Comment by jpfairbanks** [comment]
Yeah I agree that this doesn't have to be the most feature complete. The next step is to look at the other PR and run the advection diffusion physics on this new mesh.

**Comment by lukem12345** [comment]
Some package in the current Decapode tooling ecosystem is making it so that I cannot use the \leq symbol in the `makeSphere` function. `<=` works for now, but I feel like this needs to be tracked down.

**Pull request closed without merging**
