### PR TITLE
The Klausmeier Model

### PR DESCRIPTION
**Pull request by lukem12345**
# Klausmeier
We present here the Klausmeier Decapode, which represents the model of vegetation and water dynamics in semi-arid environments given by Christopher Klausmeier in his 1999 paper "Regular and Irregular Patterns in Semiarid Vegetation".

## Why Klausmeier

This model is interesting for a few reasons:
- All parameters have some physical interpretation e.g. "rainfall"
- It is a climate model
- Certain parameters yield regular traveling waves
- The dynamics are visually striking
- It combines a reaction-diffusion system with advection via a Lie derivative
- We can generalize it via the Lie derivative to examine the dynamics as water flows according to different vector fields
- It follows Turing's tradition of answering how patterns in nature can be explained via PDEs

### CODE REVIEW

**Comment by lukem12345** [comment]
The current total build time for docs (including this new Klausmeier page) is 22:53.

**Comment by jpfairbanks** [comment]
@lukem12345, This just needs to be updated to use the component array interface, then it LGTM.

**Comment by lukem12345** [comment]
@quffaro Can you add the using DiagrammaticEquations and DE.Deca lines please?

**Comment by quffaro** [comment]
@lukem12345 passes review

**Review by quffaro — APPROVED** [review]
We've reviewed this in person. Looks good.

**Pull request merged**
